name: quiz_app_frontend
description: Simple quiz app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '^3.10.1'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.5
  

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4


flutter:
  uses-material-design: true
